// ==UserScript==
// @name				Dark Instagram by Snow
// @namespace		https://github.com/sn-o-w/ig-dark-mode
// @description	Dark mode implementation for Instagram.
// @author			Snow
// @version			0.1
// @match				*://www.instagram.com/*
// @updateURL		https://raw.githack.com/sn-o-w/ig-dark-mode/master/ig-dark-mode.user.js
// @downloadURL	https://raw.githack.com/sn-o-w/ig-dark-mode/master/ig-dark-mode.user.js
// @run-at			document-start
// ==/UserScript==
(function() {var css = [
	"/* Black background for <body>, useful in the first milisecs when the page is loaded */",
	"body {",
	"    background: rgb(7, 7, 7) !important;",
	"}",
	"",
	"/* Elements on a page you are blocked (and/or it was blocked by Instagram?!) */",
	".-cx-PRIVATE-ErrorPage__errorContainer__ {",
	"    color: #fff !important;",
	"}",
	".-cx-PRIVATE-NavBar__root__ {",
	"    background-color: #000 !important;",
	"    border-bottom: 1px solid #646464 !important;",
	"}",
	".-cx-PRIVATE-NavBar__logo__ {",
	"    filter: invert(1) !important;",
	"}",
	".-cx-PRIVATE-NavBar__username__{",
	"    color: #0081ff !important;",
	"}",
	".-cx-PRIVATE-ErrorPage__errorContainer__ a, .-cx-PRIVATE-ErrorPage__errorContainer__ a:visited {",
	"    color: #0081ff !important;",
	"}",
	".-cx-PRIVATE-Footer__navItems__ a, .-cx-PRIVATE-Footer__navItems__ a:active, .-cx-PRIVATE-Footer__navItems__ a:focus, .-cx-PRIVATE-Footer__navItems__ a:hover, .-cx-PRIVATE-Footer__navItems__ a:visited {",
	"    color: #0081ff !important;",
	"}",
	".-cx-PRIVATE-Footer__copyright__{",
	"    color: #fff !important;",
	"}",
	"",
	"/* Elements based off https://userstyles.org/styles/181121 + some of them are modified */",
	"html, body, div, nav, article {",
	"    /* Username links */",
	"    --fe0: 0, 155, 255 !important;",
	"    ",
	"    /* Text and Usernames */",
	"    --i1d: 255, 255, 255 !important;",
	"    ",
	"    /* Username and Like count */",
	"    --f75: 255, 255, 255 !important;",
	"    ",
	"    /* Link Color and Time Labels */",
	"    --f52: 161, 161, 161 !important;",
	"    --ie3: 113, 113, 113 !important;",
	"    --ba8: 87, 87, 87 !important;",
	"    --c8c: 87, 87, 87 !important;",
	"    --e22: 100, 100, 100 !important;",
	"    --edc: 100, 100, 100 !important;",
	"    ",
	"    /* Borders */",
	"    --b38: 100, 100, 100 !important;",
	"    --b6a: 100, 100, 100 !important;",
	"    --ca6: 100, 100, 100 !important;",
	"    ",
	"    /* Spacerbar */",
	"    --ce3: 100, 100, 100 !important;",
	"    --bb2: 21, 21, 21 !important;",
	"    --a97: 7, 7, 7 !important;",
	"    ",
	"    /* Main Background */",
	"    --b3f: 7, 7, 7 !important;",
	"    ",
	"    /* Header Backgrounds */",
	"    --d87: 0, 0, 0 !important;",
	"    --f23: 0, 0, 0 !important;",
	"}",
	"",
	"/* Inside \"Switch Accounts\", the circle border for accounts' pics is barely visible, let's fix this */",
	"._2dbep::after {",
	"    border: 1px solid #1c1c1c !important;",
	"}",
	"",
	"/* \"Create New Post\" -> Elements like slider used for \"Filters\" and \"Adjustments\" + button when you add multiple photos + background for photo */",
	"._75ypG.RpHCb {",
	"    filter: invert(1);",
	"}",
	"._75ypG.RpHCb::-webkit-slider-thumb {",
	"    background: #000;",
	"}",
	".z-nxm {",
	"    border: 1px solid #dbdbdb !important;",
	"}",
	".z-nxm:active {",
	"    background-color: #efefef !important;",
	"}",
	"._FsHZ > div:last-child {",
	"    background: #282828 !important;",
	"}",
	"/* Elements appearing in the main page, on the right, below \"Suggestions For You\" */",
	".SkY6J .K5OFK, .SkY6J .l93RR, .SkY6J .DINPA {",
	"    color: #b4b4b4 !important;",
	"}",
	"",
	"/* Search bar */",
	".pbgfb, .XTCLo.x3qfX {",
	"    background: #1e1e1e !important;",
	"}",
	"",
	"/* White-ish background behind focused post and after clicking more options on a account (\"Block this user\", \"Restrict...\") */",
	"._2dDPU.QPGbb.CkGkG {",
	"   background-color: rgba(255,255,255,.2) !important;",
	"}",
	".RnEpo.Yx5HN {",
	"   background-color: rgba(255,255,255,.35) !important;",
	"}",
	"",
	"/* White shadow for account dropdown menu + Activity menu at the top right + search results rectangular thing */",
	".uo5MA, .AvhYw {",
	"    box-shadow: 0 0 5px 1px rgba(255,255,255,.3) !important;",
	"}",
	"",
	"/* White shadow for \"New Posts\" button (very tricky to make it appearing, just refresh page and scroll down fast, if you don't scroll down the main feed might automatically update, preventing \"New Posts\" to show up) */",
	".tCibT.dGjo4 {",
	"    box-shadow: 0 10px 45px rgba(255,255,255,.3) !important;",
	"}",
	"",
	"/* Logo visible at the top left, except Stories page */",
	"/* Added :not(a) to not invert Instagram logo appearing while viewing Stories */",
	"/* Added orange-ish color for ::selection to imitate the blue selection rectangle + light gray for ::selection:window-inactive for dark gray-ish of selection while inactive window (notice we do this to display the inverted color!) */",
	":not(a) > .s4Iyt {",
	"    filter: invert(1) !important;",
	"}",
	":not(a) > .s4Iyt::selection {",
	"    background-color: #ffa232 !important;",
	"}",
	":not(a) > .s4Iyt::selection:window-inactive {",
	"    background-color: #9d9d9d !important;",
	"}",
	"/* Specific rectangle blue selection within Firefox for Instagram logo */",
	":not(a) > .s4Iyt::-moz-selection {",
	"    background-color: #ff8728 !important;",
	"}",
	"/* The above doesn't/can't work for Firefox, lol. Within Firefox you cannot change color of any selection when window is inactive. :( */",
	":not(a) > .s4Iyt::-moz-selection:-moz-window-inactive {",
	"    background-color: #a5a5a5 !important;",
	"}",
	"",
	"/* 3 dots for more options, icons on the nav bar and posts and other elements */",
	"/* Added [color=\"#262626\"] to not change red color of like activated button [for liked posts & liked replies] and blue color of check mark (inside \"Switch Accounts\" thing) */",
	"/* Added \":not(.lC6p0.ybXk5)\" to not interfere with elements related to \"Create new post\" */",
	":not(.lC6p0.ybXk5) > ._8-yf5[color=\"#262626\"] {",
	"    filter: invert(1) !important;",
	"}",
	"",
	"/* Rectangle containing IG account(s), for people selected for sharing a post with AND/OR to start new message with (similar to dark theme of Instagram mobile app)*/",
	"/* For account name I've added extra classes (.gtFbE.xLCgt.MMzan) because otherwise they might interfere with totally different elements */",
	".ItkAi.WKY0a.pjcA_ {",
	"    background: linear-gradient(to right, #007dd1, #45cffe); !important;",
	"}",
	".gtFbE.xLCgt.MMzan {",
	"    color: #fff !important;",
	"}",
	"button.wpO6b.ZQScA>div.QBdPU>svg._8-yf5[color=\"#0095f6\"] {",
	"    color: #fff !important;",
	"}",
	"",
	"/* Back button, for example when you report an account */",
	".glyphsSpriteChevron_left__outline__24__grey_9 {",
	"    filter: invert(1) !important;",
	"}",
	"",
	"/* Selected option for instance for reporting account + these selections: https://instagram.com/push/web/settings/ || set white background for :checked to look alike the selected circular things inside dark theme of Instagram mobile app */",
	".z79H6._4SmVs:checked {",
	"    background: rgb(255,255,255) !important;",
	"}",
	"",
	"/* Used for dropdown menu when you temporarily deactivate acc, here: https://instagram.com/accounts/remove/request/temporary/ || MAYBE OTHER DROPDOWN MENUS?! */",
	"select.zOJg-.iFMgT {",
	"    color: #717171 !important;",
	"    background: #000 !important;",
	"}",
	"select.zOJg-:not(.iFMgT) {",
	"    color: #d9d9d9 !important;",
	"    background: #000 !important;",
	"}",
	"",
	"/* Gray-ish color for live viewer counter */",
	".GmxQl {",
	"    background: #808080 !important;",
	"}",
	"",
	"/* Black-ish border for \"LIVE\" badge used over avatar (similar to dark theme of mobile Instagram app, but more gray-ish in order to have a visible border) */",
	"._1iHbP:not([style*=\"border: 0px\"]) {",
	"    border: 4px solid rgb(60, 60, 60) !important;",
	"}",
	"",
	"/* There is some sort of shadow above and below any live's player, remove the shadow */",
	".KIxil {",
	"    background: transparent !important;",
	"}",
	"",
	"/* Left and/or right circular button used to browse between accounts, for instance for \"Suggested\" and/or \"Suggestions For You\" */",
	".Szr5J.POSa_, .Szr5J._6CZji {",
	"    filter: invert(1) !important;",
	"}",
	"",
	"/* Text on disabled/inactive blue buttons */",
	".L3NKy[disabled] {",
	"    color: rgba(104, 94, 94, 1) !important;",
	"}",
	"",
	"/* Reload button */",
	".coreSpriteReload {",
	"    filter: invert(1) !important;",
	"}",
	"",
	"/* Text beneath reload button => \"Unable to load suggestions.\" (perhaps other elements?!) */",
	".JMO_o {",
	"    color: #fff !important;",
	"}",
	"",
	"/* Silhouette + check mark for following channel button (Next to \"Message\" button on a account page you're following)*/",
	".glyphsSpriteFriend_Follow {",
	"    filter: invert(1) !important;",
	"}",
	"",
	"/* Symbol (paper airplane inside the circle), when no person is selected, here: https://instagram.com/direct/inbox/ */",
	".glyphsSpriteDirect__outline__96 {",
	"    filter: invert(1) !important;",
	"}",
	"",
	"/* 'Silhouette in a speech balloon, inside a circle: 1)for \"No Photos\" in \"Tagged\" section of a public account; 2)for \"Photos of You\" in \"Tagged\" page of your account (this seems to not appear always?! have 2 accs, I only see this in 1 acc) */",
	"div.coreSpriteTaggedNull {",
	"    filter: invert(1) !important;",
	"}",
	"",
	"/* 'Silhouette in a speech balloon, inside a circle, on a public account page with no posts + When you see mini-previews: 1)Lock symbol for private account; 2)camera symbol above \"No Posts Yet\"; AND PERHAPS OTHER ELEMENTS IN CIRCLES?! */",
	".FuWoR.-wdIA {",
	"    filter: invert(1) !important;",

/* CIRCLE AND/OR BORDER CIRCLE NOT USED ANYMORE?! */
/*
	"    box-shadow: 0 1px 1px -1px rgba(38, 38, 38, .5) !important;",
*/

	"}",
	"",
	"/* Partnership account name's text, for posts where there are paid partnerships, example: https://instagram.com/p/CUStncQoXV6/ ||| https://i.imgur.com/0rHFmIJ.png */",
	".FPmhX.DXJP0 {",
	"    color: #fff !important;",
	"",
	"}",
	"/* Much lighter color for numbers used here: instagram.com/directory/profiles/ + instagram.com/directory/hashtags/ */",
	"._7kTyW {",
	"    color: #fff !important;",
	"}",
	"",
	"/* The bottom long line for \"Sensitive Content\", above \"See Video\" (in both stories and posts) */",

/* W4P49 used for other elements as well, need more time to investigate */
/*
	".W4P49 {",
	"    background-color: #dbdbdb !important;",
	"}",
*/

	".DGV6U {",
	"    border-top: 1px solid #dbdbdb !important;",
	"}",
	"",
	"/* Current locations in minimaps + pin symbol next to locations + menu for maps' data, here: https://instagram.com/session/login_activity/ */",
	"div.qF0y9.Igw0E.IwRSH.eGOV_._4EzTm.pjcA_ > div._7UhW9.xLCgt.qyrsm.KV-D4.uL8Hv {",
	"    color: #000 !important;",
	"}",
	".glyphsSpriteLocation__outline__24__grey_9.u-__7 {",
	"    filter: invert(1) !important;",
	"}",
	".iMofo.t1tHE.LpqwJ, ._18Jen.LpqwJ {",
	"    background: #000 !important;",
	"}",
	"",
	"/* Lighter loading circle (some elements that are not really the loading circle have no [style], so add [style]) */",
	"[data-visualcompletion=\"loading-state\"][style] {",
	"    filter: invert(1) !important;",
	"}",
	"",
	"/* Lighter dots beneath of any post containing multiple photos and/or video, shown in main feed/main Instagram page */",
	"._19dxx .Yi5aA {",
	"    background: #a8a8a8 !important;",
	"}",
	"._19dxx .XCodT {",
	"    background: #0195f7 !important;",
	"}",
	"",
	"/* Lighter color for pending loading account's names and avatars for first post & \"Suggestions for You\" on the right, both in main page + hightlights if exist on accounts' pages + elements mentioned earlier, in a direct post (all these happen in the first second of Instagram page load) */",
	".QOqBd, .OzqB_, ._8VIOK, .u9F97, ._-9WeM, ._7JZQt, .VcOAj, .qfAOE, .kAlZ6, .HE3mO, .EIuhb, .RdURl {",
	"    background: #212121 !important;",
	"}",
	".LO-7C {",
	"    border: 2px solid #3a3a3a !important;",
	"}",
	".WidCF {",
	"    filter: invert(92.5%) !important;",
	"}",
	"",
	"/* Lock symbol when you log in and you're asked to save your login or not */",
	"span.coreSpriteKeyhole {",
	"    filter: invert(1) !important;",
	"}",
	"",
	"/* Logo visible in login page */",
	".coreSpriteLoggedOutWordmark {",
	"    filter: invert(1) !important;",
	"}",
	"",
	"/* More visibile \"Log in with Facebook\" at login page */",
	".KPnG0 {",
	"    color: #4b6cb4 !important;",
	"}",
	"",
	"/* Ligher \"Meta\" text, for instance here: https://instagram.com/accounts/edit/ */",
	"g[clip-path=\"url(#a)\"] > path:first-child {",
	"    filter: invert(1) !important;",
	"}",
	"",
	"/* Stuff for Help section, for instance here: https://instagram.com/settings/help/ */",
	"div[data-bloks-name=\"bk.components.VisibilityExtension\"]>div[data-bloks-name=\"bk.components.Collection\"], [data-bloks-name=\"ig.components.screens.Screen\"] {",
	"    filter: invert(1) !important;",
	"}",
	"span[data-bloks-name=\"bk.components.Text\"][style*=\"color: rgb(0, 55, 107)\"] {",
	"    color: rgb(255, 100, 0) !important;",
	"}",
	"span[data-bloks-name=\"bk.components.Text\"], span[data-bloks-name=\"bk.components.TextSpan\"]:not([style*=\"font-weight\"]) {",
	"    color: #000 !important;",
	"    font-weight: 500 !important;",
	"}",
	"span[data-bloks-name=\"bk.components.Text\"], span[data-bloks-name=\"bk.components.TextSpan\"][style*=\"font-weight: 700\"] {",
	"    color: #000 !important;",
	"    font-weight: 900 !important;",
	"}",
	"div[data-bloks-name=\"ig.components.screens.Navbar\"]>div>div:nth-child(2) {",
	"    color: #000 !important;",
	"    font-weight: 700 !important;",
	"}",
	"span[data-bloks-name=\"bk.components.Text\"][style*=\"white-space: pre-wrap\"] {",
	"    font-weight: 500 !important;",
	"}",
	"div[data-bloks-name=\"ig.components.screens.Navbar\"] ._8-yf5[color=\"#262626\"], div[data-bloks-name=\"ig.components.screens.Screen\"] [data-visualcompletion=\"loading-state\"][style] {",
	"    filter: invert(0) !important;",
	"}",
	"span[data-bloks-name=\"bk.components.Text\"]::selection, span[data-bloks-name=\"bk.components.TextSpan\"]::selection, div[data-bloks-name=\"ig.components.screens.Navbar\"]>div>div:nth-child(2)::selection {",
	"    background-color: #ffa233 !important;",
	"    color: #000 !important;",
	"}"
].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node);
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
	}
}
})();
